# Generated by Django 4.2.7 on 2023-12-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_course_loginlog_normalhomework_operationlog_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(blank=True, default="无", max_length=1000, null=True),
        ),
    ]
