# Generated by Django 4.2.7 on 2023-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(default='数据库', max_length=123, verbose_name='所选课程，temp，以后要改成外键'),
        ),
    ]
