# Generated by Django 4.2.7 on 2023-11-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='NormalHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='作业开始时间')),
                ('end_time', models.DateTimeField(verbose_name='作业结束时间')),
                ('content', models.CharField(max_length=1000, verbose_name='作业内容')),
                ('belong_to_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course', verbose_name='隶属课程')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course', verbose_name='所选课程'),
        ),
    ]
