# Generated by Django 4.2.7 on 2023-11-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course_normalhomework_alter_user_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course',
            new_name='selected_course',
        ),
    ]
