# Generated by Django 4.2.7 on 2023-12-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_category_remove_user_selected_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalhomework',
            name='title',
            field=models.CharField(default='无题目', max_length=100, verbose_name='作业题目'),
        ),
    ]
