# Generated by Django 4.2.7 on 2023-12-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=20)),
                ('time', models.DateTimeField(verbose_name='登录时间')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_module', models.CharField(max_length=20)),
                ('api', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('browser', models.CharField(max_length=20)),
                ('time', models.DateTimeField(verbose_name='操作时间')),
                ('status', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='markdownPictures/', verbose_name='图片')),
            ],
        ),
    ]
